# Generated by Django 5.0 on 2023-12-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, null=True)),
                ('bot_token', models.CharField(blank=True, max_length=255, null=True)),
                ('welcome_message', models.CharField(blank=True, max_length=255, null=True)),
                ('enable_auto_reply_one_to_one', models.BooleanField(default=False)),
                ('enable_auto_reply_groups', models.BooleanField(default=False)),
                ('enable_urls', models.TextField(blank=True, null=True)),
                ('delete_messages', models.TextField(blank=True, null=True)),
                ('enable_banning_user', models.BooleanField(default=False)),
                ('max_warn_count', models.IntegerField(blank=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('update_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('bot_token', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('redirect_link', models.CharField(blank=True, choices=[('/chatbot', 'Chatbot Page'), ('/other_page', 'Other Page')], max_length=100, null=True)),
            ],
        ),
    ]
