# Generated by Django 5.0 on 2023-12-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotdata',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
