# Generated by Django 5.0 on 2023-12-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_chatbotdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotdata',
            name='active',
        ),
        migrations.AddField(
            model_name='botoptions',
            name='bot_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
