# Generated by Django 5.0 on 2023-12-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='redirect_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
