# Generated by Django 5.0 on 2023-12-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_chatbotdata_active_botoptions_bot_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, null=True)),
                ('bot_token', models.CharField(max_length=100)),
            ],
        ),
    ]
