# Generated by Django 5.0 on 2023-12-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userbotdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotdata',
            name='user',
        ),
    ]
